name: NVMe_Temperatur
version: "1.0"
slug: nvme_temp
description: Zeigt die Temperatur der NVMe SSD an
startup: services
boot: auto
hassio_api: true
host_network: true
privileged:
  - SYS_ADMIN
options: {}
schema: {}
